"use client";

import { useState } from "react";
import { AlertTriangle, BarChart3, Check, ChevronDown, Tag } from "lucide-react";

const tabs = ["General", "Fees and Pricing", "Limits", "Tiers", "Settlements"] as const;
type Tab = (typeof tabs)[number];

function Field({ label, value, suffix, active = false }: { label: string; value: string; suffix?: string; active?: boolean }) {
  return <label className="min-w-0 flex-1 font-sf-pro"><span className="mb-2 block text-sm text-ink-soft">{label}</span><span className={`flex h-[45px] items-center justify-between rounded-[12px] border bg-surface-input px-3 text-sm text-ink-muted ${active ? "border-app-green" : "border-light-gray/10"}`}>{value}{suffix && <span className="flex items-center gap-4">{suffix}<ChevronDown className="size-5 text-ink-soft" /></span>}</span></label>;
}
function Switch({ on = true }: { on?: boolean }) {
  return <span className={`flex h-[25px] w-[49px] items-center rounded-full p-0.5 ${on ? "justify-end bg-app-green/30" : "bg-surface-overlay"}`}><span className={`size-7 rounded-full ${on ? "bg-app-green" : "bg-ink-muted"}`} /></span>;
}
function SectionHeader({ title, description, button }: { title: string; description: string; button?: string }) {
  return <div className="flex min-h-[65px] items-center justify-between rounded-[12px] bg-panel-gradient px-2.5"><div><h3 className="font-sf-pro text-base font-bold">{title}</h3><p className="font-sf-pro text-sm text-ink-muted">{description}</p></div>{button && <button className="h-[45px] min-w-[170px] rounded-[12px] bg-app-blue/60 px-5 font-sf-pro font-bold text-ink-muted">{button}</button>}</div>;
}
function Panel({ children }: { children: React.ReactNode }) {
  return <section className="rounded-[12px] border border-light-gray/10 bg-app-black p-[15px]"><div className="rounded-[12px] bg-surface-base p-2.5">{children}</div></section>;
}
function Governance() {
  return <section className="rounded-[12px] border border-light-gray/10 bg-surface-base p-2.5 font-sf-pro"><div className="mb-2 flex justify-between"><h3 className="font-bold text-ink-soft">Governance Logs</h3><button className="text-sm font-bold text-app-blue">View full audit</button></div>{[0,1,2].map((row) => <div key={row} className="mb-2 grid h-[30px] grid-cols-[38px_1fr_1fr_80px] items-center gap-2 text-xs"><span className="text-ink-muted">13:10</span><span className="rounded-[7px] border border-light-gray/10 bg-surface-raised px-2 py-1.5 text-accent-gold">System Config Updated</span><span className="text-center text-ink-muted">By admin{row ? " (Festus)" : ""}</span><b className="text-app-green">Success</b></div>)}</section>;
}
function PageIntro({ title, description, action, warning }: { title: string; description?: string; action?: string; warning?: boolean }) {
  return <section className="flex min-h-[76px] items-center justify-between rounded-[12px] border border-light-gray/10 bg-app-black px-[15px]"><div><h2 className="font-sf-pro text-xl font-bold">{title}</h2>{description && <p className="font-sf-pro text-sm text-ink-muted">{description}</p>}</div>{warning ? <div className="flex min-h-[64px] w-[430px] items-center gap-3 rounded-[12px] bg-app-yellow/15 px-[15px]"><AlertTriangle className="size-6 text-app-yellow" fill="currentColor" /><div><b className="text-app-yellow">High-Risk Action</b><p className="text-sm text-app-yellow/80">Changes here affect live transactions and revenue.</p></div></div> : action && <button className="h-11 min-w-[307px] rounded-[12px] bg-accent-cyan font-bold">{action}</button>}</section>;
}

function General() {
  return <><PageIntro title="General Settings" action="Save Changes" /><Panel><h3 className="mb-4 flex items-center gap-2 font-bold"><span className="flex size-5 items-center justify-center rounded bg-app-blue text-black"><BarChart3 className="size-3" /></span>Core Customization</h3><div className="grid grid-cols-2 gap-4"><Field label="Platform Name" value="Scales Plc" /><Field label="Support Email" value="Support@scales.com" /><Field label="Primary Currency" value="NGN (₦)" /><Field label="Default Time zone" value="(GMT + 01:00) Lagos" /></div><div className="mt-4 rounded-[16px] bg-black p-[15px]"><h3 className="font-bold">System Availability</h3><div className="mt-2 flex h-8 items-center justify-between rounded bg-surface-neutral px-2 text-sm font-bold text-ink-muted"><span>System Status</span><span className="text-app-green">Stable</span></div><div className="mt-3 flex justify-between"><div><b className="text-sm text-ink-soft">Maintenance Mode</b><p className="text-xs text-ink-muted">Offline status for all user, this will send a notification to them</p></div><Switch on={false} /></div><div className="mt-3 flex justify-between"><div><b className="text-sm text-ink-soft">New Registrations</b><p className="text-xs text-ink-muted">Allow onboarding of new users</p></div><Switch /></div></div></Panel><section className="grid grid-cols-2 gap-9 rounded-[12px] bg-app-black p-[25px]"><div><h3 className="font-bold">POS Configuration</h3><p className="text-sm text-ink-muted">Device behavior and firmware settings</p><div className="mt-4 space-y-4"><Field label="Auto sync interval" value="Every 5 minutes" suffix=" " /><Field label="Max transaction per POS" value="₦500,000" suffix=" " /><div className="flex justify-between text-sm"><span>Enable offline mode</span><Switch /></div></div></div><div><h3 className="font-bold">Security & Compliance</h3><p className="text-sm text-ink-muted">Authentication and AML controls</p><div className="mt-4 flex justify-between text-sm"><span>Require 2FA for Admins</span><Switch /></div><div className="mt-4 space-y-4"><Field label="Auto logout after" value="15 minutes" suffix=" " /><Field label="Flag transactions above" value="₦5,000,000" suffix=" " /></div></div></section><Governance /></>;
}
function Fees() {
  return <><PageIntro title="Fees and Pricing" description="Transaction costs across ecosystem" warning /><Panel><SectionHeader title="Consumer Fees" description="Fees charged to individual users" button="Update Fees" /><h3 className="mb-4 mt-6 flex justify-between font-bold">Wallet → Bank Transfer <Tag className="size-5 fill-accent-gold text-accent-gold" /></h3><div className="flex gap-2.5"><Field label="Standard Fee" value="₦20" /><Field label="Plus/Premium Fee" value="₦0" /><Field label="After Limit" value="₦30" /></div></Panel><Panel><SectionHeader title="Merchant MDR (Business Fees)" description="Merchant Discount Rate for business transactions" button="Update Fees" />{[["Pay-with-Transfer","1.30%"],["Local Cards","1.30%"]].map(([title,value]) => <div key={title} className="mt-6"><h3 className="mb-3 font-bold">{title}</h3><div className="flex gap-2.5"><Field label="Standard Tier" value={value} suffix="Percentage" /><Field label="Titanium Tier" value={title === "Pay-with-Transfer" ? "₦1,150" : value} suffix={title === "Pay-with-Transfer" ? "Fiat" : "Percentage"} /><Field label="Diamond Tier" value={value} suffix="Percentage" /></div></div>)}<div className="mt-6"><h3 className="mb-3 font-bold">International Cards</h3><div className="flex gap-2.5"><Field label="Rate" value="4.30%" /><Field label="FX Markup" value="1.30%" /></div></div></Panel></>;
}
function Limits() {
  return <><PageIntro title="Limits and Security" description="Configure global settings constraints, financial ceilings and protective measures for the ledger ecosystem" /><Panel><SectionHeader title="Consumer Limits" description="Transaction and balance limits for individual users" button="Save Limits" /><h3 className="mb-4 mt-6 font-bold">Daily Transfer Limit</h3><div className="flex gap-2.5"><Field label="Standard Fee" value="₦150,000" /><Field label="Plus/Premium Fee" value="₦2,500,000" /><Field label="Maximum Balance" value="₦5,000,000" /></div></Panel><Panel><SectionHeader title="Business Limits" description="Limits for business accounts" button="Save Limits" /><h3 className="mb-4 mt-6 font-bold">Daily Withdrawal Limits</h3><div className="flex gap-2.5"><Field label="Standard Fee" value="₦500,000" /><Field label="Plus/Premium Fee" value="₦5,000,000" /><Field label="Diamond Tier" value="Unlimited" /></div></Panel><Panel><SectionHeader title="Fraud Controls" description="Risk management and velocity controls" button="Save Control" /><div className="mt-14 flex gap-2.5"><Field label="Maximum Transactions per minute" value="10" /><Field label="Velocity Threshold" value="Price" /><Field label=" " value="Time (minutes)" /></div></Panel><Governance /></>;
}
function Perks() { return <div className="mt-5 flex gap-2.5">{["Standard Ledger","Priority Support","Bulk Loan Approval"].map((perk) => <span key={perk} className="flex items-center gap-2 rounded-[8px] bg-app-blue/20 px-2.5 py-3 text-sm text-app-blue">{perk}<Check className="size-4 rounded-full bg-app-blue p-0.5 text-black" /></span>)}</div>; }
function Tiers() {
  return <><PageIntro title="Tiers and Sovereign Configurations" description="Define sovereign thresholds and eligibility parameters for consumer and business accounts" action="Add Tier" /><Panel><SectionHeader title="Consumer Tiers" description="Define upgrade requirements for user tiers" button="Save Limits" /><h3 className="mb-4 mt-6 font-bold">Premium Tier Requirements</h3><div className="flex gap-2.5"><Field label="Minimum Balance" value="₦200,000" /><Field label="Monthly Spend (OR)" value="₦500,000" /></div><Perks /></Panel><Panel><SectionHeader title="Business Tiers" description="Define requirements for business tier upgrades" button="Save Limits" />{[["Titanium Tier","₦32,000,000","₦5,000,000"],["Diamond Tier","₦150,000,000","₦50,000,000"]].map(([title,balance,volume]) => <div key={title} className="mt-7"><h3 className="mb-4 font-bold">{title}</h3><div className="flex gap-2.5"><Field label="Minimum Balance" value={balance} active /><Field label="Monthly Volume" value={volume} active /></div><Perks /></div>)}</Panel><Panel><SectionHeader title="Global Logic Rules" description="General Parameters" /><div className="mt-6 grid grid-cols-2 gap-6 rounded-[12px] bg-app-black p-6">{["Automated Tier Upgrades","Grace Period Alerts","Tier Maintenance Mode","Legacy Migration"].map((label,index) => <div key={label} className="flex justify-between text-sm text-ink-soft"><span>{label}</span><Switch on={index !== 2} /></div>)}</div></Panel><Governance /></>;
}
function Settlements() {
  return <><PageIntro title="Settlements" description="Define, Configure when and how settlements are processed" /><Panel><SectionHeader title="Settlement Schedule" description="Configure when and how settlements are processed" button="Save Settlements Rules" /><div className="mt-14 flex gap-2.5"><Field label="Standard Settlement" value="T+1 Next Day)" suffix=" " /><Field label="Settlement Time" value="Select time" /></div><h3 className="mt-6 font-bold">Instant Settlement</h3><div className="mt-4 flex justify-between"><div><b className="text-sm text-ink-soft">Enable Instant Settlement</b><p className="text-xs text-ink-muted">Allow businesses to request instant payouts</p></div><Switch /></div><div className="mt-4"><Field label="Instant Settlement Fee" value="1.30%" suffix="Percentage" /></div><h3 className="mt-6 font-bold">Retry Logic</h3><div className="mt-4 flex gap-2.5"><Field label="Retry Interval" value="Every 10 minutes" suffix=" " /><Field label="Maximum Retries" value="5" /><Field label="Failure Attempt Alert Threshold" value="3" /></div></Panel><Governance /></>;
}

export default function SystemControlTabs() {
  const [active, setActive] = useState<Tab>("General");
  return <div className="space-y-[15px]"><nav className="grid grid-cols-5 gap-4">{tabs.map((tab) => <button key={tab} onClick={() => setActive(tab)} className={`h-11 rounded-[12px] font-sf-pro text-base ${active === tab ? "border border-app-green/30 bg-app-green/20 font-bold text-white" : "text-ink-muted"}`}>{tab}</button>)}</nav>{active === "General" && <General />}{active === "Fees and Pricing" && <Fees />}{active === "Limits" && <Limits />}{active === "Tiers" && <Tiers />}{active === "Settlements" && <Settlements />}</div>;
}
