"use client"

import { useRouter } from "next/navigation"
import TruncatedIdentifier from "@/components/TruncatedIdentifier"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import type { AdminBusiness } from "@/lib/scale9/admin-models"

export default function BusinessTable({ businesses }: { businesses: AdminBusiness[] }) {
  const router = useRouter()
  return <Table className="border-separate border-spacing-y-[10px] p-0"><TableHeader><TableRow className="border-none">{["Business Name", "Business ID", "Owner", "KYB Status", "Monthly Volume", "Status"].map((heading) => <TableHead key={heading} className={`px-[15px] py-[10px] text-sm font-bold text-white ${heading === "Status" ? "text-right" : ""}`}>{heading}</TableHead>)}</TableRow></TableHeader><TableBody>{businesses.map((business) => <TableRow key={business.id} tabIndex={0} onClick={() => router.push(`/businesses/${business.id}`)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") router.push(`/businesses/${business.id}`) }} className="h-[55px] cursor-pointer border-none outline-none focus-visible:[&>td]:border-app-blue/60"><TableCell className="rounded-l-[8px] border-y border-l border-ink-soft/10 bg-surface-raised px-[15px] text-base font-bold text-white">{business.name}</TableCell><TableCell className="w-[145px] max-w-[145px] border-y border-ink-soft/10 bg-surface-raised px-[15px] text-sm font-bold text-white"><TruncatedIdentifier value={business.id} className="max-w-[115px]" /></TableCell><TableCell className="border-y border-ink-soft/10 bg-surface-raised px-[15px] text-base text-ink-dim">{business.owner}</TableCell><TableCell className="border-y border-ink-soft/10 bg-surface-raised px-[15px]"><VerificationStatus verified={business.verified} /></TableCell><TableCell className="border-y border-ink-soft/10 bg-surface-raised px-[15px] text-base font-medium text-white">—</TableCell><TableCell className="rounded-r-[8px] border-y border-r border-ink-soft/10 bg-surface-raised px-[15px] text-right"><span className={`inline-block w-[107px] rounded-[7px] p-1.5 text-center text-sm ${business.active ? "bg-app-green/5 text-app-green" : "bg-app-red/5 text-app-red"}`}>{business.active ? "Active" : "Inactive"}</span></TableCell></TableRow>)}</TableBody></Table>
}

function VerificationStatus({ verified }: { verified: boolean }) { return <span className={`inline-flex items-center gap-2 text-sm font-medium ${verified ? "text-app-blue" : "text-app-red"}`}><span aria-hidden="true" className={`size-2 rounded-full ${verified ? "bg-app-blue" : "bg-app-red"}`} />{verified ? "Verified" : "Unverified"}</span> }
